name = "celo-atari-games-api"
main = "src/index.ts"
compatibility_date = "2024-05-14"
compatibility_flags = ["nodejs_compat"]

[vars]
VITE_CHAIN_ID = "42220"
VITE_SCORE_REGISTRY_ADDRESS = "0xf26ed81d52ae4a106344f5739d767e3d603f8370"

[[kv_namespaces]]
binding = "SESSIONS"
id = "e3046d5d21f04b8abfbbc329eeda1c7e"

[[d1_databases]]
binding = "DB"
database_name = "celo-arcade-db"
database_id = "04a8ae6f-e91f-4c14-840d-de8dc74ce0fb"
